#!/usr/bin/env bash
# scripts/install-hooks.sh — リポジトリローカル git hook を .git/hooks/ にインストールする
#
# 用途: 新規クローン後に 1 回実行する。CLAUDE.md の運用ルールでも呼ばれる。
# 何をするか: docs/adr/*.md の変更を検知したら scripts/generate_adr_index.py を
# 実行し、生成された INDEX.md をステージングに追加する pre-commit hook を作成。

set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
HOOK_PATH="$REPO_ROOT/.git/hooks/pre-commit"

cat > "$HOOK_PATH" <<'HOOK_EOF'
#!/usr/bin/env bash
# Auto-generated by scripts/install-hooks.sh — do not edit manually.
set -e

REPO_ROOT="$(git rev-parse --show-toplevel)"

# docs/adr/ 配下の ADR が変更された場合のみ INDEX.md を再生成する
if git diff --cached --name-only | grep -qE '^docs/adr/[0-9]{4}-.*\.md$'; then
  echo "[pre-commit] docs/adr/ 変更を検知 → INDEX.md を再生成"
  python3 "$REPO_ROOT/scripts/generate_adr_index.py"
  git add "$REPO_ROOT/docs/adr/INDEX.md"
fi
HOOK_EOF

chmod +x "$HOOK_PATH"
echo "Installed pre-commit hook at: $HOOK_PATH"
